<h1>[@Edit post]</h1>

<? $u = $this->entry // just easier ?>

<script>

    function validate()
    {
        nicEditors.findEditor('post-text').saveContent();

        var title = $.trim($('#post-title').val());
        var text  = $.trim($('#post-text').val());

        if (title == '' || text == '' || text == '<br>')
        {
            alert('[@You must specify all fields before submitting the blog post!]');
            return false;
        }
        else
            return true;
    }

    $(function() {
        new nicEditor({iconsPath : '/blog/js/nicEditorIcons.gif'}).panelInstance('post-text');
    });

</script>

<!--
    Remember that in ANY OUTPUT of user data (whether from database or not) we always
    run it through html() which escapes it properly. This guards against CSS attacks.
-->

<form method="post">
    <!-- NF_IV injection. Creates an <input type="hidden"> thing -->
    <?= $this->form ?>
    <label class="left-label" for="post-title">Title</label>
    <input type="text" id="post-title" name="title" style="width: 40em" placeholder="[@Enter the title of the post here]" value="<?= html($u->title) ?>">
    <br>
    <br>
    <textarea id="post-text" name="text" style="width: 100%" rows="15" placeholder="[@Enter the blogpost body here]"><?= html($u->text) ?></textarea>
    <br>
    <button type="submit" onclick="return validate()"><img src="/blog/img/fatcow/accept.png"> Save</button>
</form>
