<div style="float: right">
    <button type="button" onclick="location.href='<?= $this->ref('edit') ?>'"><img src="/img/fatcow/add.png"> [@Write new]</button>
</div>

<script>

    function remove(id)
    {
        if (confirm('[@Are you sure you want to delete the blog post with id] ' + id + '?'))
        {
            $.post('<?= $this->ref('delete') ?>', {id: id}, function() {
                location.reload();
            });
        }
    }

</script>

<style>

    .remove { height: 16px; width: 16px; cursor: pointer; }

</style>

<h1>Blog posts</h1>

<br>

<table width="100%">
    <col width="5%">
    <col width="60%">
    <col width="15%">
    <col width="15%">
    <col width="5%">
    <tr>
        <th>[@ID]</th>
        <th>[@Title]</th>
        <th>[@Written]</th>
        <th>[@Author]</th>
        <th>[@Remove]</th>
    </tr>
    <? foreach($this->entries as $u): ?>
        <tr>
            <td><a href="<?= $this->ref('edit', $u->id) ?>"><?= $u->id ?></a></td>
            <td><a href="<?= $this->ref('edit', $u->id) ?>"><?= html($u->title) ?></a></td>
            <td class="nobr"><?= $u->created ?></td>
            <td class="nobr"><?= $u->objUser ? html($u->objUser->fullname) : '?' ?></td>
            <td align="center"><img class="remove" src="/img/fatcow/cross.png" onclick="remove(<?= $u->id ?>)"></td>
        </tr>
    <? endforeach ?>
</table>

<br>
<? Paginator::render(20, Data_BlogEntry::getPostCount()) ?>