<?php

/**
 * Test class for NF_Page.
 * Generated by PHPUnit on 2010-07-19 at 16:13:04.
 */
class NF_PageTest extends PHPUnit_Framework_TestCase
{
    protected function setUp()
    {
        NF::request()->handleExceptions = false;
        NF::request()->clear();

        NF_Path::$pages = NF_Path::$root . 'test/sys/page/TestPages/';
    }

    public function testInvoke()
    {
        global $testValue;

        $req = clone NF::request();

        $req->_path = '/test-page/view';
        $req->invoke();
        $this->assertEquals($testValue, 'iVf');

        $req->_path = '/test-page/edit';
        $req->id = 2;
        $req->invoke();
        $this->assertEquals($testValue, 'iE2f');

        $req->_path = '/test-page/post-data';
        $req->var1 = 9;
        $req->invoke();
        $this->assertEquals($testValue, 'iP29xf');

        $req->_path = '/test-page/post-data';
        $req->var2 = '#';
        $req->invoke();
        $this->assertEquals($testValue, 'iP29#f');
    }

    public function testFaultyInvoke()
    {
        $this->setExpectedException('NF_Exception');

        NF::request()->_path = '/test-page/edit';
        NF::request()->invoke();
    }

    public function testPageNotFound()
    {
        $this->setExpectedException('NF_EPageNotFound');

        NF::request()->_path = '/test-nonexistent/view';
        NF::request()->invoke();
    }
}
