<h1>[@Edit user]</h1>

<? $u = $this->user ?>

<script>

    function validate()
    {
        var fullname = $.trim($('#user-fullname').val());
        var username = $.trim($('#user-username').val());
        var email    = $.trim($('#user-email').val());

        if (fullname == '' || username == '' || email == '')
        {
            alert('[@You must specify all fields before submitting the form]');
            return false;
        }
        else
            return true;
    }

</script>

<form method="post">
    <?= $this->form ?>

    <label class="left-label" for="user-fullname">[@Full name]</label>
    <input type="text" id="user-fullname" name="fullname" style="width: 30em" placeholder="[@e.g. John Adams]" value="<?= html($u->fullname) ?>">
    <br>

    <label class="left-label" for="user-username">[@Username/login]</label>
    <input type="text" id="user-username" name="username" style="width: 30em" placeholder="[@e.g. jadams]" value="<?= html($u->username) ?>">
    <br>

    <label class="left-label" for="user-email">[@Email address]</label>
    <input type="text" id="user-email" name="email" style="width: 30em" placeholder="[@e.g. jadams@gmail.com]" value="<?= html($u->email) ?>">
    <br>

    <br>

    <label class="left-label" for="user-password">[@Set new password]</label>
    <input type="password" id="user-password" name="password" style="width: 30em" placeholder="[@If you need a new password, enter it here]">
    <br>

    <br>

    <button type="submit" onclick="return validate()"><img src="/blog/img/fatcow/accept.png"> [@Save]</button>
</form>
