<div style="float: right">
    <button type="button" onclick="location.href='<?= $this->ref('edit') ?>'"><img src="/img/fatcow/add.png"> [@Add new user]</button>
</div>

<script>

    function remove(id)
    {
        if (confirm('[@Are you sure you want to delete the user with id] ' + id + '? [@All posts written by this user will remain and must be deleted manually.]'))
        {
            // This creates a POST ajax call to /admin/users/delete?id=...
            $.post('<?= $this->ref('delete') ?>', {id: id}, function() {
                location.reload();
            });
        }
    }

</script>

<style>

    .remove { height: 16px; width: 16px; cursor: pointer; }

</style>

<h1>[@Blog posts]</h1>

<br>

<table width="100%">
    <col>
    <col>
    <col>
    <col width="5%">
    <tr>
        <th>[@Full name]</th>
        <th>[@User name / login]</th>
        <th>[@Email]</th>
        <th>[@Remove]</th>
    </tr>
    <? foreach($this->users as $u): ?>
        <tr>
            <td><a href="<?= $this->ref('edit', $u->id) ?>"><?= html($u->fullname) ?></a></td>
            <td><a href="<?= $this->ref('edit', $u->id) ?>"><?= html($u->username) ?></a></td>
            <td><a href="<?= $this->ref('edit', $u->id) ?>"><?= html($u->email) ?></a></td>
            <td align="center">
                <img class="remove" src="/img/fatcow/cross.png" onclick="remove(<?= $u->id ?>)">
            </td>
        </tr>
    <? endforeach ?>
</table>
