<!doctype html>
<html>
    <!-- This is the main template. It always gets evaluated as part of the main code in
         public/index.php, and is run after everything else. All the content produced
         by the pages gets inserted here.

         Notice that $Response->content is only just one of the things you can set...
         if you need to produce custom menus, custom footers, or several different
         templates/layouts, you can load different templates through the $Response
         object and variables. Basically $Response acts as a template too, so setting
         $Response->menuStuff makes it available as $this->menuStuff in here. -->
    <head>
        <!-- Set the title. This can be done manually through $Response->title if need be -->
        <title><@title></title>
        <!-- This is where all the JS files will be linked to, in settings.conf -->
        <@js>
        <!-- Link to all specified CSS files -->
        <@css>
        <!-- Any other header tags programmatically defined gets inserted here -->
        <@head>
        <!-- Master scripts -->
        <script>

            function setLanguage(lang)
            {
                // Make an AJAX call to Index->executeSetLang($id) to set the language.
                // Then reload the page upon success.
                $.get('/index/set-lang', {id: lang}, function() {
                    location.reload();
                });
            }

        </script>
    </head>
    <body>
        <div id="wrapper">
            <div id="header">
                <div id="bkg">
                    <h1><a href="/"><?= html($Application->appTitle) ?></a></h1>
                </div>
            </div>
            <div id="content">
                <!-- This is where all the $Response->content stuff goes. -->
                <!-- We use "@content" as a short form... we could also have written the PHP equivalent -->
                <!-- of "echo $this->content;" directly. -->
                <@content>
            </div>
            <div id="footer">
                <div style="float: right">
                    <a href="javascript:setLanguage('en')"><img src="/img/silk-flags/us.png"></a>&nbsp;
                    <a href="javascript:setLanguage('sv')"><img src="/img/silk-flags/se.png"></a>
                </div>
                <? if ($Session->uid): ?>
                    <!-- This gets shown if we have an authenticated session -->
                    <p>
                        [@Logged in as] <a href="/admin/user/view/<?= $Session->uid ?>"><?= html($Session->fullname) ?></a>
                    </p>
                    <ul>
                        <li><a href="/">[@Main site]</a></li>
                        <li><a href="/admin/main">[@Admin main menu]</a></li>
                        <li><a href="/rss"><img src="/img/rss.png" valign="absmiddle"> [@RSS feed]</a></li>
                        <li><a href="/admin/logout">[@Log out]</a></li>
                    </ul>
                <? else: ?>
                    <!-- This gets shown if we have just a normal, unauthenticated session -->
                    <ul>
                        <li><a href="/">[@Home]</a></li>
                        <li><a href="/rss"><img src="/img/rss.png" valign="absmiddle"> [@RSS feed]</a></li>
                        <li><a href="/admin">[@Admin]</a></li>
                    </ul>
                <? endif ?>
            </div>
        </div>
    </body>
</html>
