<script>

    function remove(id)
    {
        if (confirm('[@Are you sure you want to delete the comment with id] ' + id + '?'))
        {
            $.post('<?= $this->ref('delete') ?>', {id: id}, function() {
                location.reload();
            });
        }
    }

</script>

<style>

    .remove { height: 16px; width: 16px; cursor: pointer; }
    .text   { color: blue; }

</style>

<h1>[@Comments]</h1>

<br>

<table width="100%">
    <tr>
        <th>[@ID]</th>
        <th>[@Signed]</th>
        <th>[@Email]</th>
        <th>[@IP address]</th>
        <th>[@Blog entry]</th>
        <th>[@Remove]</th>
    </tr>
    <? foreach($this->comments as $u): ?>
        <tr>
            <td><?= $u->id ?></a></td>
            <td><?= html($u->signed) ?></td>
            <td><?= html($u->email) ?></td>
            <td><?= html($u->ip) ?></td>
            <td><?= $u->objEntry ? html($u->objEntry->title) : '?' ?></td>
            <td align="center"><img class="remove" src="/img/fatcow/cross.png" onclick="remove(<?= $u->id ?>)"></td>
        </tr>
        <tr>
            <td></td>
            <td colspan="5" class="text"><?= nl2br(html($u->text)) ?></td>
        </tr>
    <? endforeach ?>
</table>

<br>
<? Paginator::render(20, Data_BlogComment::getCommentCount()) ?>